runtime: image

image:
  url: https://hub.docker.com/layers/nocodb/nocodb/0.9.31/images/sha256-2df4871a627fb115370585b6c169554d91f42564f79a3c7801301a3f107f8a96?context=explore
  envVars:
      - key: postgres://ouerghi:2duiLwGssWGjjdFtt8CifXZvmNthmd0h@dpg-cj8g5bdjeehc73bvfefg-a/dbnocodb_jm22
        fromDatabase:
          name: dbnocodb_jm22
          property: connectionString 